version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver
    environment:
      SA_PASSWORD: "Test@123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql
    networks:
      - superhero-net

  webapi:
    build:
      context: ./dotnet-api
      dockerfile: Dockerfile
    container_name: webapi
    environment:
      - DB_CONNECTION_STRING=Server=sqlserver,1433;Database=SuperHeros;User Id=SA;Password=Test@123;TrustServerCertificate=True;
    depends_on:
      - sqlserver
    expose:
      - "80"
    networks:
      - superhero-net

  frontend:
    build:
      context: ./react-app
      dockerfile: Dockerfile
    container_name: frontend
    depends_on:
      - webapi
    expose:
      - "80"
    networks:
      - superhero-net

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - frontend
      - webapi
    networks:
      - superhero-net

networks:
  superhero-net:  
    driver: bridge

volumes:
  sql_data:
